import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Oasis Infobyte - Landing page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
