name: Deploy Next.js site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Export to HTML
        run: npm run export

      # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy artifacts
        run: |
          mkdir -p deploy
          cp -R ${{ github.workspace }}/out/* deploy/
        working-directory: ./deploy
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
      - name: Initialize Git repository
        run: |
          git init
          git add .
          git commit -m 'Deploy to GitHub Pages'
      - name: Push changes
        uses: actions/upload-artifact@v2
        with:
          name: exported-site
          path: ./deploy
